services:
  wa-gateway:
    image: azharfa/wa-gateway:latest
    container_name: wa-gateway-service
    restart: unless-stopped
    ports:
      # Format: "Port_VPS : Port_Internal_Container"
      - "8003:8080"
    volumes:
      # Mapping folder wa-data di VPS ke folder /app/data di dalam container
      # Ini menjaga sessions.db aman meskipun container dihapus/diupdate
      - ./wa-data:/app/data
    environment:
      - TZ=Asia/Jakarta
      - JWT_SECRET=${JWT_SECRET:-ketikan_disini_secret_anda}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-ketikan_disini_secret_anda}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-AdminSekolah123}
      - GIN_MODE=release